### ISSUE TITLE
[frontend][landing] Add more Menu entries

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid-landing-page#47]
We need to add these menu entries:
Quem Somos
Privacidade
Perguntas Frequentes

It may or may not be together with the other options:
Para que serve?
Como usar?

If they are joined together, the order should be:
Para que serve?
Como usar?
Quem Somos
Privacidade
Perguntas Frequentes

**Comment by geiras** [comment]
**MOBILE**
![image](https://user-images.githubusercontent.com/22840903/78499374-37753400-7748-11ea-8063-bb7f2253e5dd.png)

Since the available width is small and hiding the options behind a menu would make pages difficult to find, I suggest that we add the remaining menu items bellow the main picture
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3974%3A6211

---

**DESKTOP**
![image](https://user-images.githubusercontent.com/22840903/78499430-920e9000-7748-11ea-8a64-1ed967fe6555.png)

We have space to include all menu items on the desktop version.
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3974%3A5523

**Comment by pfortuna** [comment]
This approach is approved but we'll need a new submenu for all other pages (but only on mobile). Can you please add them here @geiras?

**Comment by geiras** [comment]
I suggest this menu for all the secondary pages:

![image](https://user-images.githubusercontent.com/22840903/78510909-8e066080-7790-11ea-88cc-1c032a586dae.png)

**MENU CLOSED**
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=4007%3A7571

**MENU OPEN**
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=4007%3A7582
